### ISSUE TITLE
Add a new API to allow custom client options

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#106]
Proposed API
```cs
public AzureAppConfigurationOptions ConfigureClientOptions(Action<ConfigurationClientOptions> options)
```
This API should allow a user to overwirte the properties of `ConfigurationClientOptions` we use by default.

For example, in the case of Azure/AppConfiguration#179, the customer can do
```cs
using HttpClient client = new HttpClient(
    new HttpClientHandler()
    {
        Proxy = new WebProxy(new Uri("http://example.com"))
    });

builder.AddAzureAppConfiguration(o =>
    o.Connect(...)
     .ConfigureClientOptions(co => co.Transport = new HttpClientTransport(client));
)
```
Reference [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy).

cc: @drago-draganov @jimmyca15

**Comment by abhilasharora** [comment]
This feature has been released as a part of version `3.0.0` of the package `Microsoft.Extensions.Configuration.AzureAppConfiguration`.
