### ISSUE TITLE
Consider adding logging for TryRefreshAsync method

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#134]
Add logging for failures during `IConfigurationRefresher.TryRefreshAsync` to allow users to fix errors during the refresh operation. Check the discussion in https://github.com/Azure/AppConfiguration-DotnetProvider/pull/119 for more details. Also allow users of the middleware to register an `ILogger` to retrieve failure logs.

**Comment by zhenlan** [comment]
@avanigupta @jimmyca15 

While it's useful to add logs when anything goes wrong during the refresh, it's also helpful whenever a configuration update has happened. Users need a positive signal to confirm a successful configuration update. Is this something we can add?

**Comment by avanigupta** [comment]
Sure, we could add an informational log every time `IConfiguration` is updated by a refresh operation. To keep it simple, we could start with a single log entry when anything is updated:
`IConfiguration updated from Azure App Configuration.` 

Alternatively, we could provide more details by indicating which type of key-value changed. For example:
`Key Vault secret(s) updated from Azure Key Vault.`
`Feature Flag(s) updated from Azure App Configuration.`
`Key-Value(s) updated from Azure App Configuration.`

Or if `LoadAll()` was triggered:
`IConfiguration updated from Azure App Configuration.`

**Comment by zhenlan** [comment]
Sounds good, @avanigupta. What's the difference between the first and the third?

**Comment by avanigupta** [comment]
I meant that we have two options:

**Option 1:** A single log for any kind of changes: 
    - `IConfiguration updated from Azure App Configuration.`


**Option 2:** Multiple logs indicating which type of key-value changed - this will further be divided into two categories and we will pick the log depending on the condition:

A. `LoadAll()` was triggered so the entire configuration was updated:
        - `IConfiguration updated from Azure App Configuration.`
        
OR

B. `LoadAll()` was not triggered but something specific was updated (could be 1, 2 or all 3 types were updated during the same refresh operation):
    - `Key Vault secret(s) updated from Azure Key Vault.`
    - `Feature Flag(s) updated from Azure App Configuration.`
    - `Key-Value(s) updated from Azure App Configuration.`

**Comment by jimmyca15** [comment]
That sounds like a debugging scenario to me. What's the motivation for this?

**Comment by zhenlan** [comment]
This is not for debugging. It creates the full circle for change and health monitoring. For example, in our service, we like to see logs whenever a change happened - either it's a cert rotation or it's a resource cleanup. In the config provider, we are making changes on behalf of the users, if we don't log those changes, users will have a hard time adding their own.

@avanigupta how about 2.A *and* 2.B? I think it's important to see the specific logs for [secret rotation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/reload-key-vault-secrets-dotnet).

**Comment by lissdy** [comment]
Echo here, may I know the progress of the feature? We are considering adding logs by ourselves to notify configuration changes.

**Comment by zhenlan** [comment]
Error/warning logs are already supported in the latest release of the provider library.

This PR is adding informational logs: #354
