### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by DavidNorena** [Azure/AppConfiguration-DotnetProvider#140]
Im having the following issue when I debug from docker 

![image](https://user-images.githubusercontent.com/26279057/76068137-9a638780-5f5e-11ea-94fe-3874d3ab1a63.png)

but the same connection string works without debugging docker

**Comment by zhenlan** [comment]
Is it possible that the clock of the docker container is not correct? "The access token has expired” error occurs when HTTP request header Date is more than 15min off from the server time.

**Comment by DavidNorena** [comment]
It was sync with server, but Im gonna wait for the issue to raise again, if so, ill re-open this, thank you !
