### ISSUE TITLE
Allow access to configuration settings

### ISSUE THREAD

**Issue by WimVergouwe** [Azure/AppConfiguration-DotnetProvider#155]
I'm using Azure App Configuration to configure multiple microservices. With this setup it's quite nice to be able to configure settings on an environment level that get shared by all microservices. I can easily scope the settings to a specific microservice by using labels. So far so good.

One of these microservices hosts an SPA frontend (Blazor WebAssembly). I'd like to be able to expose some of the settings to this frontend. To avoid exposing too much, I'm only going to expose settings which have a specific tag. 

In order to achieve this, I need access to the 'raw' `ConfigurationSetting` objects in `_settings` field of `AzureAppConfigurationProvider` class. I don't want to query Azure App Configuration myself, because I would need to make sure the logic is 100% the same as in the configuration provider. Furthermore, I would also need to implement all the robustness features that are present in the configuration provider.

I think it would be possible to do this through the `IOfflineCache` and deserializing the data. But this is quite a hack and doesn't seem very future proof. Would you guys be open to a PR with something like `IConfigurationAccess` that would allow access to the `ConfigurationSetting` objects whenever they change in the configuration provider?

**Comment by zhenlan** [comment]
@WimVergouwe good suggestion. It makes sense to me.

I am thinking about another overload of the `Select` API that takes in a lambda (besides key & label filters) that takes in `ConfigurationSetting`.

Add more folks for the design discussion. @abhilasharora @jimmyca15 @drago-draganov

**Comment by drago-draganov** [comment]
That's been in the plan somewhere. We're waiting for the official SDK support to expose ConfigurationSetting instance. We should also allow the lambda to return ConfigurationSetting instance. That way we open up for custom mapping.

**Comment by jimmyca15** [comment]
I'm wondering if we and go all the way and make it possible to access ConfigurationSettings rather than relying on a lambda callback.

**Comment by jimmyca15** [comment]
IConfiguration already exposes a change token. That's effectively the callback.

**Comment by zhenlan** [comment]
@jimmyca15 that sounds like a good idea too.

**Comment by drago-draganov** [comment]
We shouldn't expose ConfigurationSetting instances from IConfiguration. That may indeed create the false assumption that a change in ConfigurationSetting instance will reflect a change in configuration system and along the chain (IOptions pattern, etc.).

**Comment by jimmyca15** [comment]
As Zhenlan and Drago mentioned, it should be possible to utilize the custom mapping API we planned to accomplish this. We didn't have an issue for it yet so I put one up. https://github.com/Azure/AppConfiguration-DotnetProvider/issues/157

**Comment by zhenlan** [comment]
I am closing this issue as the plan is tracked in the new issue Jimmy opened.
