### ISSUE TITLE
Throw an exception if ConfigureRefresh is called without any refresh registrations

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#162]
We want to be able to prevent users from calling `ConfigureRefresh` with no key-values registered for refresh using the `Register` method. The current behavior is to allow users to retrieve an instance of the refresher without registering any key-value for refresh. However, it does not have a fully working use case and could lead to confusion in behavior when `ConfigureRefresh` is used more than once with different initializer.

After this change, the following code should throw an exception with an error message indicating that `ConfigureRefresh` cannot be used without any refresh registration.

```` csharp
IConfiguration configuration = builder.Build();

builder.AddAzureAppConfiguration(options =>
{
    options.Connect(configuration["connection_string"])
            .ConfigureRefresh(refresh =>
            {
                refresh.SetCacheExpiration(TimeSpan.FromSeconds(10));
            });

    _refresher = options.GetRefresher();
});
````

**Comment by zhenlan** [comment]
Which line will throw, `options.GetRefresher()`?

Do we get any customer complaints about current behavior? Not sure if this worth the breaking change.

**Comment by abhilasharora** [comment]
When the user calls `builder.Build()`, then we can validate the registrations made in `ConfigureRefresh`. If we don't find any key-value registered for refresh, we will throw an exception.

We haven't received any customer complaint. However, while discussing PR https://github.com/Azure/AppConfiguration-DotnetProvider/pull/161 with Jimmy, we figured that we don't have a use case where we would want to allow users to call `ConfigureRefresh` without any registration. So disallowing it would help avoid code that could be confusing on its purpose and behavior.

**Comment by zhenlan** [comment]
How can I recover from the initial config load failure then?

**Comment by zhenlan** [comment]
Include this in v4 release as it's a breaking change.

**Comment by abhilasharora** [comment]
The fix has been released as a part of the version `4.0.0` of the package.
https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/4.0.0

**Comment by SeanFeldman** [comment]
What's the guidance for the use cases where all keys have the same refresh and there are many keys?
With the current API, the only option is to specify the refresh rate for each one. Is there any alternative?

**Comment by abhilasharora** [comment]
@SeanFeldman The cache expiration time configured using the `SetCacheExpiration` method is applicable for all key-value pairs (except feature flags), and cannot be set per key. Could you clarify what you mean by specifying refresh rate for each one?

**Comment by SeanFeldman** [comment]
@abhilasharora, reading issue description
> We want to be able to prevent users from calling ConfigureRefresh with no key-values registered for refresh using the Register method.

and looking at the sample
https://github.com/Azure/AppConfiguration-DotnetProvider/blob/939f7a178d391b6e85b0ddac9b7c76a744b959a7/examples/ConsoleApplication/Program.cs#L50-L61

it looks like one has to register every key and provide a cache expiration value.

**Comment by abhilasharora** [comment]
@SeanFeldman Thanks for the clarification. At this time, the `ConfigureRefresh` method only supports registration of specific keys for refresh. No call to `Register` means the refresh won't happen for changes in _any_ key-value, and does not mean that refresh would happen for _all_ key-values. For scenarios that need all settings in the `Select` clause to be refreshed, the recommended approach is to add a sentinel key and register refresh for it with `refreshAll: true` as in the code sample. This will ensure that if the value changes for this specific key, then all settings are refreshed.

The call to `SetCacheExpiration` is optional. If no such call exists, the default cache expiration time of 30 seconds is used.

**Comment by DavidBoike** [comment]
In that case, let me restate the question. What is the best way to set the cache time for ALL keys so that the app doesn’t hammer away at the service to refresh every key every 30 seconds when all the values are _mostly_ static?

Preferably without having to register each key individually.

**Comment by abhilasharora** [comment]
@DavidBoike The following code selects all key-values to be loaded at startup. It registers the key named `Sentinel` for refresh and sets the cache expiration time to 60 seconds. For each invocation of `RefreshAsync` or `TryRefreshAsync` method, it checks the time elapsed since the last call to the server was made for this key.

If less than 60 seconds have elapsed, no call to the server is made. If 60 seconds or more have elapsed, a single call to the server is made to fetch the updated value of `Sentinel` key, if changed. If the value for this key has actually changed, then additional calls to the server are made to retrieve updated value of all settings in batches of 100 settings per request. So if I have 250 settings in App Configuration, then every 60 seconds, 1 call would be made to fetch the value of `Sentinel` key, and only if that value has changed, 3 more calls would be made to the server to fetch the updated value of all 250 settings.

In this approach, a user can update one or more settings in App Configuration, and then change the value of the `Sentinel` key to indicate that the settings are consistent and the updated values are ready to be retrieved by the application through refresh. This also prevents the application from retrieving inconsistent set of settings while the user is in the middle of updating a set of inter-related settings.

```` csharp
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration(options =>
{
    options.Connect(settings["connection_string"])
           .Select(KeyFilter.Any)
           .ConfigureRefresh(refresh =>
           {
               refresh.Register("Sentinel", refreshAll: true)
                      .SetCacheExpiration(TimeSpan.FromSeconds(60));
           });
}
````

**Comment by michaelmcdaniel** [comment]
How does this work with exclusively using only feature toggles?  Do we now have to specify a variable that we must update in order to change the value of the feature toggle without explicitly listing all the feature toggles?

**Comment by abhilasharora** [comment]
@michaelmcdaniel The `UseFeatureFlags` method automatically registers refresh for all feature flags. It has its own [settings](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.featuremanagement.featureflagoptions) for cache expiration time. For applications that only care about refresg only for feature flags, the `ConfigureRefresh` method is not needed.
