### ISSUE TITLE
Allow refresh registration for for Complex objects

### ISSUE THREAD

**Issue by preardon** [Azure/AppConfiguration-DotnetProvider#164]
Given the current configuration:

```
{
  "config" : {
    "Key1" : "Value1",
    "Key2" : "Value2",
    "Key3" : "Value3",
    "Key4" : "Value4",
  }
}
```

doing the following will fail with a 404
```
    config.AddAzureAppConfiguration(options => options.Connect(
            new Uri(builtConfig[_appConfigKey]),
            credentials)
         .ConfigureRefresh(refresh =>
        {
             refresh.Register("config", refreshAll: true)
                .SetCacheExpiration(new TimeSpan(0, 5, 0));
        })
        .ConfigureKeyVault(kv => { kv.SetCredential(credentials); })
            .UseFeatureFlags()
    );
```

![image](https://user-images.githubusercontent.com/7712876/83156866-d724c200-a0fa-11ea-8339-a30d7869f1b5.png)

It appears that the code currently calls RefreshKeyValueCollections however the only object that can populate the MultiKeyWatchers IEnumerable is private and in the UseFeatureFlags() Method.

It would be nice to be able to register my own types

**Comment by zhenlan** [comment]
The scenario is valid. This needs the server-side support of change detection for a collection of keys so the client-side can do this efficiently.

The work is tracked in the issue Azure/AppConfiguration#153, so I am going to close this one.

cc: @drago-draganov
