### ISSUE TITLE
Configuration refresh does not work when ChainedConfigurationProvider is used

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#168]
## Problem
A user added the App Configuration middleware to their application, but the configuration is not refreshed.

## Cause
The `AzureAppConfigurationProvider` could be nested under a `ChainedConfigurationProvider` if the user calls `IConfigurationBulder.AddConfiguration(...)` to add configuration built from the App Configuration provider.

Unfortunately, `ChainedConfigurationProvider` does not provide a way for others to access its child providers. This caused the issue that the App Configuration middleware could not find the instance of `AzureAppConfigurationProvider` and thus cannot obtain the instance of `IConfigurationRefresher`.

## Proposal
There is no good solution to this. One idea from @drago-draganov is we provide an alternative API for users to call (the name is to be finalized)
```cs
public static IConfigurationBuilder AddConfiguration2(this IConfigurationBuilder configurationBuilder, IConfiguration config);
```
Under the cover, this API will add a type derived from `ChainedConfigurationProvider` and this type we write exposes child providers.

As part of fixing #166, we can provide additional information and suggest users to call this new API in the exception message.

## Reference
The code of `ChainedConfigurationProvider` can be found at
https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Configuration/src

cc: @drago-draganov @abhilasharora @jimmyca15

**Comment by cwe1ss** [comment]
I also can't get the refresh to work with .NET 7 RC2 and the new minimal API-style Program.cs. I also have a `ChainedConfigurationProvider` in my list of providers:

![image](https://user-images.githubusercontent.com/4581460/195696362-e427ed08-a65d-4daf-973d-6ce893758688.png)

Is there any workaround for this?

**Comment by zhenlan** [comment]
Please add App Configuration provider directly to your configuration builder instead of nested under the `ChainedConfigurationProvider`. Here is a code sample for .NET 6.

https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core6x#reload-data-from-app-configuration

**Comment by cwe1ss** [comment]
Thank you for the quick response! I have been using that link for my implementation. 

I did some more quick testing and the `ChainedConfigurationProvider` is already there from the beginning:
![image](https://user-images.githubusercontent.com/4581460/195705794-c379129f-a998-419d-948b-de2872dee965.png)

And here's how it looks after `AddAzureAppConfiguration()`:
![image](https://user-images.githubusercontent.com/4581460/195705932-5fd61b75-2dde-4360-a84b-741b2b5e98b7.png)

The `AzureAppConfigurationProvider` has been added to the list and isn't a child of `ChainedConfigurationProvider`.

Anything else I can do?

**Comment by zhenlan** [comment]
Is this a web app? If so, you should also add App Configuration middleware as instructed in the same document. It will take care of the configuration refresh.

If it's a console app, you will need to call `TryRefreshAsync` in your code to get the configuration refreshed. You can find more details in this doc for a console app.
https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core

**Comment by cwe1ss** [comment]
I'm so sorry, I seem to have just stopped reading after the step to add `builder.Services.AddAzureAppConfiguration()`. One shouldn't program late at night 😪 

thank you very much for your help, it is working now.

**Comment by kevinferretti** [comment]
Now that the `ChainedConfigurationProvider` exposes its `IConfiguration` as per https://github.com/dotnet/runtime/issues/44486, is this issue able to be fixed?

**Comment by zhenlan** [comment]
Yes, but that's only available in .NET 7.

@avanigupta, we need to code this so it will "light up" when running in a .NET 7 app.
