### ISSUE TITLE
Cache expiration is ignored on first call to RefreshAsync

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#172]
After initial load of the configuration, if a setting is included in `Select` and also registered for refresh, the first call to `RefreshAsync` would ignore the cache expiration interval specified by the user and always revalidate and refresh the that setting. The expected behavior is to respect the cache expiration interval even for the first call to refresh.

**Comment by avanigupta** [comment]
The fix has been released in package version 4.1.0:
- [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/)
- [Microsoft.Azure.AppConfiguration.AspNetCore](https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/)
