### ISSUE TITLE
Allow users to select only feature flags in configuration provider

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#182]

**Comment by amerjusupovic** [comment]
Below is an example of the current approach we recommend to select only feature flags.

    configurationBuilder.AddAzureAppConfiguration(options =>
    {
        options.Connect(Environment.GetEnvironmentVariable("ConnectionString"))
               .Select("_")
               .UseFeatureFlags();
    });

The default `Select` query includes all key-values with a `null` label in the configuration. This code calls `Select` with an obscure `KeyFilter` to essentially skip the default query.
