### ISSUE TITLE
Allow users to pass ClientId in CorrelationId

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#188]
For users that use the configuration provider from multiple machines with the same Client IP address, there is currently no reliable way to use the logs to determine the specific machine that sent a request. We want to allow users to pass a random string `ClientId` (preferably host name) in the `CorrelationId` header that could be used for this purpose.

**Comment by avanigupta** [comment]
Users can set [DiagnosticsOptions.ApplicationId](https://learn.microsoft.com/en-us/dotnet/api/azure.core.diagnosticsoptions.applicationid?view=azure-dotnet) property to differentiate between multiple clients with same IP address. 

I don't think this issue is valid anymore.
