### ISSUE TITLE
Deserialize configuration settings with JSON content type

### ISSUE THREAD

**Issue by avanigupta** [Azure/AppConfiguration-DotnetProvider#191]
### Overview
In order to preserve data types of non-string values in App Configuration, the "Content Type" property of settings can be leveraged. If a setting in App Configuration has a valid JSON content type and a valid JSON value, it should be deserialized by the Configuration Provider.

### Valid JSON Content Type
Media types, as defined [here](https://www.iana.org/assignments/media-types/media-types.xhtml), can be assigned to the Content Type field in App Configuration. 
A media type consists of a type and a subtype, which is further structured into a tree. A media type can optionally define a suffix and parameters:

    type "/" [tree "."] subtype ["+" suffix] *[";" parameter]

If the type is "application" and the subtype (or suffix) is "json", the media type will be considered a valid JSON type.
Some examples of valid JSON types are: 
- application/json
- application/activity+json
- application/vnd.foobar+json;charset=utf-8

### Valid JSON Values
If the value of a configuration setting can be validated using any JSON validator (like [JSONLint](https://jsonlint.com/)), it can be deserialized correctly by the Configuration Provider. If a configuration setting has valid JSON content type, but its value is not valid JSON, no deserialization will be performed and it will be treated like a string value.
Some examples of valid JSON values are:
```
- "This is some text"
- 723
- false
- null
- "2020-01-01T12:34:56.789Z"
- [1, 2, 3, 4]
- {"ObjectSetting":{"Targeting":{"Default":true,"Level":"Information"}}}
```

### Sample JSON settings in App Configuration
![image](https://user-images.githubusercontent.com/5563494/88356758-c15c0380-cd1d-11ea-81c9-00b5802a8cf6.png)

**Comment by BlowaXD** [comment]
Hello,

Any date planned for the release ?

**Comment by avanigupta** [comment]
Hi @BlowaXD , the preview version of this change has already been released. You can find the packages here:

- [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/4.0.0-preview)
- [Microsoft.Azure.AppConfiguration.AspNetCore](https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/4.0.0-preview)

Please let us know if you have any feedback as that would help us release the stable version soon.

**Comment by mwoo-o** [comment]
Hello, 
I have an Azure App Configuration that contains a key with content type of "Application/json".  
How to find out the Content type of a key? 
I see that there is Azure.Data.AppConfiguration.ConfigurationSetting class that can indicate the Content type of a Key.
However, how should we get the ConfigurationSetting from IConfiguration or Microsoft.Extensions.Configuration.ConfigurationRoot?  Is it possible to do that?

**Comment by avanigupta** [comment]
Hello @mwoo-o, if you're using the AppConfig provider library (Microsoft.Extensions.Configuration.AzureAppConfiguration) to read your key-values from Azure App Configuration, we will automatically deserialize the key-values with content type "application/json" before adding them to `IConfiguration`. Since `IConfiguration` is just a collection of key-value pairs, we cannot provide all the information of a `ConfigurationSetting` in `IConfiguration`. 
Could you explain your scenario a bit so that I can understand why you want to access the `ConfigurationSetting` from `IConfiguration`?

**Comment by mwoo-o** [comment]
In our scenario, if application provides our provider key, says key1,  in the App configuration, we are thinking to process the key1's value based on the content type.  The key value doesn't need to be only Json. It can be xml or format that are understood by our provider.    We are in the process of exploring different possibilities.

For example, If it is Json, then we can deserialize the Json value using the 
   ConfigurationBinder.Bind(azConfig, <key name>, <class instance>);

Having the class to mange it internally in our layer can provide a centralized implementation for us to work with application on premise or in cloud.

**Comment by avanigupta** [comment]
Thanks for the explanation! We are working on a new API that will allow you to do this in future: https://github.com/Azure/AppConfiguration-DotnetProvider/issues/157
Let me know if this would work for you.

**Comment by mwoo-o** [comment]
The new API seems to be the solution.  Is the new API available?

**Comment by mwoo-o** [comment]
One more question, Will the new Map API applied to all the Labels for the particular settings?

**Comment by avanigupta** [comment]
> That's great! Will we be notified when the new API is released?

Yes, we'll update the linked github issue when its released.

> Will the new Map API applied to all the Labels for the particular settings?

We will let the user transform all `ConfigurationSetting`s retrieved from Azure App Configuration service. But the user is responsible for selecting which `ConfigurationSetting`s will be retrieved from the server. For this, you can use the `Select` API to specify which keys/labels you want to load ([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.select?view=azure-dotnet)).

**Comment by mwoo-o** [comment]
Hi Avani,

Thanks a lot for your prompt responses!

On a separate note.  I am encountering some issues with the Filter 
function in .NET.

  AzureAppConfigurationOptions.Select() API.

I did the  AzureAppConfigurationOptions.Select(*)  with the assumption 
that it will return all keys for all the labels (null, "somelabel"...etc).
However, it seems that it only return keys with Null label.

Same behavior if we don't doing filtering.  It returns all keys with 
Null label.

Is it a known issue?

Thanks
Martha

**Comment by avanigupta** [comment]
This is the intended behavior while selecting key-values from AppConfig. The `Select` API accepts prefix filtering for keys only. We don't support loading all labels at once. This is because if the same key exists for multiple labels, the final value of that key in `IConfiguration` will be ambiguous. If you want to load multiple labels, you can have multiple `Select` statements for each label that you want to load. This way, you define the explicit order in which values will be overridden if one key is loaded with multiple labels. For example, you can specify the following:
```
 var configurationBuilder = new ConfigurationBuilder()
                .AddAzureAppConfiguration(options =>
                {
                    options.Connect(new Uri("https://*****.azconfig.io"), new DefaultAzureCredential())
                           .Select(KeyFilter.Any, myLabel1)
                           .Select(KeyFilter.Any, myLabel2);
                });
```

If a key exists for both selected labels, its value corresponding to `myLabel2` will be used in `IConfiguration`.

**Comment by mwoo-o** [comment]
Hi Avani,

Thanks for the information.

I think the behavior is different to what mentioned in the Query 
key-values section of the doc:
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value

Might be the REST API supports the behavior that I want, but not the 
Azure API using AzureAppConfigurationOptions.

I agree with you with the ambiguous scenario when the same key exists 
for multiple labels.
But if there is only one key that exists in a label, there is no ambiguity.

Thanks
Martha

**Comment by avanigupta** [comment]
> Might be the REST API supports the behavior that I want, but not the Azure API using AzureAppConfigurationOptions. 

That is correct. The App Config provider library offers a layer of abstraction over the underlying REST APIs.

> I agree with you with the ambiguous scenario when the same key exists for multiple labels. But if there is only one key that exists in a label, there is no ambiguity. 

Agreed, but this is something that can only be determined at runtime. If someone unknowingly adds the same key with multiple labels, any application referencing that key will be in an unpredictable state. We want to make sure that this can never happen and users explicitly provide the labels that their app needs.

**Comment by mwoo-o** [comment]
The behavior sounds reasonable.  At the meanwhile, I don't see any issue.
Thanks for the information.
