### ISSUE TITLE
Add Support for Azure App Configuration events updating configuration.

### ISSUE THREAD

**Issue by MattMinke** [Azure/AppConfiguration-DotnetProvider#207]
Azure App Configuration can be configured to publish events. These events can be subscribed to by the same application that is using Azure App Configuration for configuration. The events published by Azure App Configuration could then be used to refresh the application's configuration. This would eliminate the need for the application to query for a changes as the changes would be published to the application through Event Grid. This would allow changes to configuration value to be propagated to the application as they happen. This would eliminate the need for the application to query for changes, and instead receive configuration changes as events. 

This would potentially eliminate the the need for the application to query for configuration changes after initialization. It would also allow configuration changes to be realized by the application possibly much sooner (depending on the value for the Cache Expiration) period. 

### Relevant Documentation
- https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-app-configuration-event
- https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-app-configuration-event

**Comment by abhilasharora** [comment]
@MattMinke Thanks for you suggestion. We already have support for using events from Event Grid to update the application configuration through push refresh, and some of our customers are currently using it in production. We are still working on adding documentation for it, so more customers can leverage this functionality.

**Comment by MattMinke** [comment]
A call to `SetDirty(TimeSpan.Zero)` followed by a call to `IConfigurationRefresher.RefreshAsync()/TryRefreshAsync()` gets really close to what I am envisioning but is not quite what I am after. The Event Grid event includes the key and label details of the configuration key that was deleted or changed, and with this information you could issue a refresh for just that individual key. This would prevent the other keys configured for refresh from being queried unnecessarily. Also in my case I would prefer to not have to list every configuration key my application uses (there are 50+) in the refresh configuration. Currently for the `IConfigurationRefresher.RefreshAsync()/TryRefreshAsync()` call to have any affect the key has to be listed in the refresh configuration.

**Comment by abhilasharora** [comment]
@MattMinke We recommend users to configure refresh for a single key with the `refreshAll` parameter set to `true`. Whenever this key is updated, all settings configured in the `Select` clause would be updated. This approach does not have the problems that you mentioned in your last response. Only a single request to App Configuration is made in order to detect changes in settings, and users don't need to update application code to configure refresh for new settings. You can find more details about it [here](https://github.com/Azure/AppConfiguration/issues/113).
