### ISSUE TITLE
Make it easier to run an event handler when settings from App Configuration change

### ISSUE THREAD

**Issue by abhilasharora** [Azure/AppConfiguration-DotnetProvider#212]
This items tracks the changes needed to allow users to be able to run some code when the settings cached by App Configuration are updated on refresh. Also update the documentation and code samples.

**Comment by avanigupta** [comment]
We can improve our documentation to suggest using [IConfiguration.GetReloadToken](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.getreloadtoken?view=dotnet-plat-ext-5.0) to watch for configuration changes.

**Comment by samsadsam** [comment]
When key values are refreshed, .NET has a [way](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.getreloadtoken?view=net-8.0&viewFallbackFrom=dotnet-plat-ext-5.0) to notify subscribers about it.

If we get more customers asking about how to achieve this, we will write it in the documentation. Closing this issue.
