### ISSUE TITLE
JsonExtensionDataAttribute not always working.

### ISSUE THREAD

**Issue by MattMinke** [Azure/AppConfiguration-DotnetProvider#213]
I have the following json as a value in Azure App configuration and the following object model. The object model has two properties decorated with the JsonExtensionDataAttributes. The Settings property on the Carrier type is being honored and working as expected while the Arguments property on the StateRule type is not.  The state properties in the JSON are being lost. 

### Actual Result: 
Property 'Arguments' does not have a key value for any of the state properties in the Json
![image](https://user-images.githubusercontent.com/5995359/99113168-039aa080-25ac-11eb-8b2e-894842494a25.png)

### Expected Result:
Property Arguments on type StateRule should have a key value for any property that does not have a matching member

### JSON: 
```JSON
[
    {
        "id": 4,
        "name": "Name",
        "active": true,
        "states": [
            {
                "name": "Add",
                "state": "WA"
            },
            {
                "name": "Add",
                "state": "CO"
            },
            {
                "name": "Add",
                "state": "OH"
            }
        ],
        "settings": {
            "contactNumber": "303-876-5309",
            "category": "s1"
        }
    }
]
```

### object model: 
```C#
public class Carrier
{
    public int? Id { get; set; }
    public string Name { get; set; }
    public bool Active { get; set; }
    public List<StateRule> States { get; set; } = new List<StateRule>();
    [JsonExtensionData]
    public Dictionary<string, object> Settings { get; set; } = new Dictionary<string, object>();
}
public class StateRule
{
    public string Name { get; set; }
    [JsonExtensionData]
    public Dictionary<string, object> Arguments { get; set; } = new Dictionary<string, object>();
}

```

### Startup.cs
```C#
public override void ConfigureServices(IServiceCollection services)
{
    ....

    services.AddOptions<List<Carrier>>()
        .Bind(Configuration.GetSection("Application:CarrierSettings"))

    ....
}
```

Image shows the state property has successfully been read from azure app configuration. 
![image](https://user-images.githubusercontent.com/5995359/99112753-650e3f80-25ab-11eb-9798-a5802c27f341.png)

**Comment by zhenlan** [comment]
If the key-value has been loaded to configuration successfully, the binding is not what App Configuration handles. With that being said, using JSON content-type may be helpful in your case.
https://docs.microsoft.com/azure/azure-app-configuration/howto-leverage-json-content-type
