### ISSUE TITLE
Refresh registered settings are not updated in offline file cache if refreshAll is false

### ISSUE THREAD

**Issue by avanigupta** [Azure/AppConfiguration-DotnetProvider#214]
If an exception occurs during startup or refreshAll scenario, we try to populate config from offline cache, if available.
However, we only update the settings in offline cache in the startup or refreshAll scenario. This means that individual key-values changes are never updated in offline cache until refreshAll is true.

For example, in this scenario:
```cs
builder.AddAzureAppConfiguration(options =>
{
    options.Connect(connectionString)
    .Select(KeyFilter.Any)
    .ConfigureRefresh(refreshOptions =>
    {
        refreshOptions.Register("TestKey1")
                      .Register("TestKey2", refreshAll: true)
                      .SetCacheExpiration(TimeSpan.FromSeconds(1));
    })
    .SetOfflineCache(new OfflineFileCache(new OfflineFileCacheOptions
    {
        Path = pathToCacheFile 
    })); 
    
    _refresher = options.GetRefresher();
});
```

Any changes in "TestKey1" will not be updated in offline file cache. So if "TestKey2" changes (refreshAll scenario is triggered) and there is an exception, we will load config from offline cache but the value of "TestKey1" will be stale.

**Comment by zhenlan** [comment]
Just want to make sure we are on the same page - the offline cache is designed *not* to be updated from the fresh. It only caches whatever loaded at the app startup.

**Comment by avanigupta** [comment]
Oh okay, so do we want to update offline cache when refreshAll scenario is triggered?
Currently we update the cache in both startup and refreshAll scenarios.

**Comment by abhilasharora** [comment]
It should be fine to retain the current behavior for now. This would be addressed as a part of the improvements we plan to make to the offline cache in a future major release.

**Comment by avanigupta** [comment]
Sure, this issue can help document the desired functionality so that we can pick it up for a future major release.

**Comment by avanigupta** [comment]
We decided to completely remove offline caching capabilities: https://github.com/Azure/AppConfiguration-Announcements/issues/20
