### ISSUE TITLE
Offline cache default path not working on clean sites/slots without the D:\home\data folder

### ISSUE THREAD

**Issue by PeterFreemarket** [Azure/AppConfiguration-DotnetProvider#216]
I've just created a new slot for my site and realized, that the call to:

```
options.SetOfflineCache(new OfflineFileCache());
```

Throws a very confusing error: "Default cache path is only supported when running inside of an Azure App Service."
The code is obviously running inside of an Azure App Service, the problem is that the D:\home\data doesn't seem to exist yet.

**Comment by abhilasharora** [comment]
@PeterFreemarket Thanks for reporting the issue. What is the runtime stack for your Azure App Service?

![image](https://user-images.githubusercontent.com/47916289/99578638-f4dc3100-2991-11eb-8f0d-edc83f6e188a.png)

**Comment by PeterFreemarket** [comment]
Hi, the runtime stack is ASP.NET V4.8

**Comment by abhilasharora** [comment]
@PeterFreemarket I'm able to reproduce this issue. As a workaround, I would suggest creating the directory `D:\home\data` manually. In a future release, we plan to make the detection of Azure Web App environment more reliable, and update code to create the `data` directory in case it doesn't already exist.

**Comment by avanigupta** [comment]
Hi @PeterFreemarket, we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?

**Comment by PeterFreemarket** [comment]
Hi @avanigupta, the motivation was to have some kind of fallback if the app configuration store is unavailable (downtime, etc..). Our app is able to run ok without the app configuration store being available, but it is not able to start without it.

**Comment by avanigupta** [comment]
We decided to completely remove offline caching capabilities. Please see this announcement for more details: https://github.com/Azure/AppConfiguration-Announcements/issues/20

**Comment by PeterFreemarket** [comment]
The recommended HA approach, while functioning, has some drawbacks:
1/ There is no out of the box synchronization functionality between the stores. I know I can create one myself, but I'm not using off the shelf solutions to create something like this myself.
2/ If using 2 or more stores one need to mark all of them as optional, so if one goes down the system is still functioning. This has the downside that if there is a configuration error, the exception will be very likely swallowed by the app configuration library making debugging really hard. Also, on the other hand, if both stores go down, the app treats both config stores as optional and continue starting up with a partial configuration.
NOTE: I'm talking from experience with using app configuration together with the .NET core configuration provider.

**Comment by zhenlan** [comment]
@PeterFreemarket, thanks for the feedback. Those are valid points. We are working on a better solution by supporting geo-replication (https://github.com/Azure/AppConfiguration/issues/178). The configuration provider will also be updated to support multiple replicas.
