### ISSUE TITLE
KeyVault retry options

### ISSUE THREAD

**Issue by kamilzzz** [Azure/AppConfiguration-DotnetProvider#232]
We should be able to provide Key Vault's SecretClientOptions in order to override default Key Vault's retry policy (if any).

Right now I think it's not possible and I'm also not sure if Key Vault by default retries 429 errors from service.

**Comment by abhilasharora** [comment]
@kamilzzz The [AzureAppConfigurationKeyVaultOptions.Register(SecretClient)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationkeyvaultoptions.register?view=azure-dotnet-preview) method within the `ConfigureKeyVault` method can be used to register a user-instantiated instance of `SecretClient`. This instance of `SecretClient` could be created using custom `SecretClientOptions` and will be used to resolve any key vault references for that specific key vault.

**Comment by kamilzzz** [comment]
@abhilasharora thanks. I missed that out...
