### ISSUE TITLE
Calling UseFeatureFlags multiple times ignores subsequent key refreshers

### ISSUE THREAD

**Issue by matthawley** [Azure/AppConfiguration-DotnetProvider#235]
We're starting to utilize Azure App Configuration to manage both a "all services" and "specific service" via the usage of labels. However when we call UseFeatureFlags multiple times, only the first call registers a multi key watcher for backend refreshing.

I believe the issue to be related to this line of code, wherein the label should also be considered when adding a new multi key watcher or not.

https://github.com/Azure/AppConfiguration-DotnetProvider/blob/74682ad09ca18fbf194fb8554ad2cb760af12cca/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationOptions.cs#L167

**Comment by avanigupta** [comment]
Hi @matthawley, currently we do not support this scenario. But we are working on introducing a new API with which you can register multiple feature flags with different labels and they will be refreshed appropriately. Please see [this PR](https://github.com/Azure/AppConfiguration-DotnetProvider/pull/234) for more details.

**Comment by matthawley** [comment]
Thanks @avanigupta - my workaround for now is to just register 2 app configuration providers.

**Comment by avanigupta** [comment]
@matthawley, the feature has been released in package version **4.3.0-preview**:

- [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/4.3.0-preview)
- [Microsoft.Azure.AppConfiguration.AspNetCore](https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/4.3.0-preview)

Please let us know if you have any feedback on the new functionality.

**Comment by avanigupta** [comment]
The stable version for this feature has been released in v4.4.0.
