### ISSUE TITLE
SetOfflineCache throws exception and expects file

### ISSUE THREAD

**Issue by sameer-kumar** [Azure/AppConfiguration-DotnetProvider#239]
Hello,

This is for an Asp.net core 3.1 project using Microsoft.Extensions.Configuration.AzureAppConfiguration 4.1.0.
Here is my registration code:

```
builder.ConfigureAppConfiguration((hostingContext, config) => {
  var env = hostingContext.HostingEnvironment;
  var contentRoot = env.ContentRootPath;
  config.AddAzureAppConfiguration(options => {
                    options.Connect("Endpoint=https://xxx.azconfig.io;Id=l6-s0/8eB;Secret=JwX=");
                     options.SetOfflineCache(new OfflineFileCache(
                        new OfflineFileCacheOptions { Path = $"{contentRoot}\\OfflineConfigStore\\OfflineCache.json" }));
                }, 
                optional: true);
};
```

When I run the app for the first time, I see a new json file generated at specified location and everything works fine. 
However, if the file is not there and an unexpected issue happens with AppConfiguration connectivity, the code throws FileNotFoundException.

> Could not find file 'E:\sample1\src\Sample1.Web\OfflineConfigStore\OfflineCache.json'.

Is it expected?

**Comment by avanigupta** [comment]
Hi @sameer-kumar, we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?

**Comment by sameer-kumar** [comment]
Thanks for reaching out. The intent here is to rely on offline cache as fallback mechanism if connection is lost or could not be established to Azure App Configuration service.

**Comment by avanigupta** [comment]
We decided to completely remove offline caching capabilities. Please see this announcement for more details: https://github.com/Azure/AppConfiguration-Announcements/issues/20
