### ISSUE TITLE
Allow Users to Provide Custom Key Value Adapters

### ISSUE THREAD

**Issue by oh-yeah** [Azure/AppConfiguration-DotnetProvider#241]
Howdy,

We are currently in the process of creating and upgrading some of our projects from .NET to NET 5.  One of the big problems we faced was app configurations, specifically how to use a single Azure AppConfiguration container for both style projects without having to duplicate hundreds of keys.  For reference, the project types previously mentioned use very different data structures to store configuration values.  Eventually we found what seemed to be the perfect solution, adding custom KeyValueAdapters to the configuration pipeline.  Creating our own KeyValueAdapters gave us the ability to perform custom mapping and also provide strict mode functionality, something missing from the core version of this package.  

I submitted PR #229 to make this project more extensible and allow developers to supply adapters to the configuration pipeline.  Please note, this also may address Issue #157.

**Comment by avanigupta** [comment]
Hi @oh-yeah, we are working on releasing the custom mapping API discussed in #157. Would that solve your problem without having to expose `IKeyValueAdapter`?

**Comment by oh-yeah** [comment]
Sorry for the delayed response, busy times.  The custom mapping API, at the surface, does seems like it would solve this issue.  Will this mapping API also allow me to perform a strict mapping mode myself?  In other words, what would happen if I opt into configuration mapping but didn't set a configuration value or return null?

**Comment by avanigupta** [comment]
if you return null for a particular `ConfigurationSetting`, that `ConfigurationSetting` will not be added to your application configuration (`IConfiguration`).

**Comment by oh-yeah** [comment]
Did the mapping api in #157 ever get pushed out?  I feel like this would meet my needs, but I'd like to run some tests to verify.

**Comment by avanigupta** [comment]
The Map API has not been released yet. We'll update #157 issue when its ready for release.

**Comment by avanigupta** [comment]
Tracking progress in #157
