### ISSUE TITLE
Using Azure AppConfiguration for Feature Flags in dotnet core worker service

### ISSUE THREAD

**Issue by svrooij** [Azure/AppConfiguration-DotnetProvider#260]
I'm trying to use Microsoft.FeatureManagement in a dotnet core worker service. But I have no clue how to configure it that it will periodically check if the feature flags have been changed.

Since it's not a asp.net core app I don't have a `Configure` and I thus cannot do `app.UseAzureAppConfiguration();`.

Do I need to call something periodically to refresh the feature flags that are configured in AppConfiguration?
And is there a sample on how to do just that?

**Program.cs (partial)**

```csharp
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)

                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    // Build config to access the current values
                    var currentConfig = config.Build();
                    // Load AZURE_APP_CONFIGURATION_URI and add app configuration if set
                    var appConfigUri = currentConfig.GetValue<string>("AZURE_APP_CONFIGURATION_URI")
                        ?? "https://my-default-config-fake.azconfig.io";

                    config.AddAzureAppConfiguration(options =>
                    {
                        var credential = new DefaultAzureCredential();

                        options
                            .Connect(new Uri(appConfigUri), credential)
                            .Select(KeyFilter.Any, LabelFilter.Null)
                            .Select(KeyFilter.Any, $"{hostingContext.HostingEnvironment.EnvironmentName}");

                        options.UseFeatureFlags(ffOptions =>
                        {
                            ffOptions.CacheExpirationInterval = TimeSpan.FromSeconds(30);
                            ffOptions
                                .Select(KeyFilter.Any, LabelFilter.Null)
                                .Select(KeyFilter.Any, $"{hostingContext.HostingEnvironment.EnvironmentName}");
                        });
                    });
                })
                .ConfigureServices(services => Startup.ConfigureServices(services))
            .UseConsoleLifetime();
```

**partial Startup.cs**

```csharp
    public static class Startup
    {
        public static void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.AddApplicationInsightsTelemetryWorkerService(options =>
            {
                options.ApplicationVersion = typeof(Program).Assembly.GetName().Version.ToString();
            });
            services.AddAzureAppConfiguration();
            services.AddFeatureManagement();
            services.AddHttpClient();
            
// Other stuff removed 

        }
    }
```

**Comment by avanigupta** [comment]
Hi @svrooij, for a .NET Core app, you need to call [`RefreshAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.iconfigurationrefresher.refreshasync) or [`TryRefreshAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.iconfigurationrefresher.tryrefreshasync) to refresh your key-values or feature flags from App Config. This call should be setup in your application hot path in a way that ensures that `TryRefreshAsync` is continuously called regardless of whether the cache has expired or not. If the cache has not expired, there will be no server calls, but if the cache has expired, the latest value will be fetched from the server. This is true for both key-values and feature flags.

You already have the correct `UseFeatureFlags` method defined in your code. As long as `TryRefreshAsync` is triggered, your feature flags will be reloaded from AppConfig every 30 seconds (your `CacheExpirationInterval`).

**Comment by shaneholder** [comment]
@svrooij you've probably figured this out by now but when you execute UseFeatureFlags a key is automatically registered to be watched.  If you do not specify a Select() in the options then a value of * is used which watches all feature flags.  You do not need to call ConfigureRefresh for FeatureFlags to refresh.

**Comment by svrooij** [comment]
I think the answer I was looking for was:

The **IConfigurationRefresherProvider** is registered when you call `.AddAzureAppConfiguration(...)`. You can use it to refresh all the configuration settings by resolving the **IConfigurationRefresherProvider** and the following code:

```csharp
foreach (var refresher in refresherProvider.Refreshers) {
  _ = refresher.TryRefreshAsync();
}
```

Is this correct? If so, this might be a great addition in the docs.

**Comment by avanigupta** [comment]
That is correct. And yes, we should add this note in our docs too. Thanks for the suggestion!

**Comment by svrooij** [comment]
I think https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-app-configuration/enable-dynamic-configuration-dotnet-core.md

can use an extra section

```plain

### Refresh configuration with dependency injection

You can also refresh the configuration by resolving the ** IConfigurationRefresherProvider** from the service collection and calling `.TryRefreshAsync` on each refresher.
```

```csharp
public class YourClass {
  private readonly IEnumerable<IConfigurationRefresher> refreshers
  public YourClass(IConfigurationRefresherProvider refresherProvider) {
    refreshers = refresherProvider.Refreshers;
  }

  public async Task SomeMethod() {
    foreach(var refresher in refreshers) {
      _ = refresher.TryRefreshAsync();
    }
  }
}
```

**Comment by amerjusupovic** [comment]
@svrooij It's been a while but we've added this into the documentation [here](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core?tabs=core6x#configuration-refresh-using-dependency-injection), as suggested. Gonna close this one out.
