### ISSUE TITLE
Namespacing for Feature Flags

### ISSUE THREAD

**Issue by shaneholder** [Azure/AppConfiguration-DotnetProvider#261]
Is there a way to namespace Feature flags using Azure App Configuration.  I have several applications connecting to a single App Configuration and would like to be able to use the same name for a feature flag in different contexts.  This would allow me to enable featureA for application A but not for application B.  I know that I can do this just by using prefixes on the names but I was hoping for something cleaner like using the : separator when creating an App Configuration entry.

Thanks,
Shane Holder

**Comment by avanigupta** [comment]
Hi @shaneholder, this work is being tracked here: https://github.com/Azure/AppConfiguration/issues/519
