### ISSUE TITLE
Please provide more examples

### ISSUE THREAD

**Issue by dluc** [Azure/AppConfiguration-DotnetProvider#263]
* How to integrate with KeyVault, while working locally, e.g. when AAD is not available
* How to integrate with KeyVault, when the app is deployed to the cloud

Thanks

**Comment by avanigupta** [comment]
Hello @dluc, please see this document for information on integrating with KeyVault in production vs development environments: [Grant your app access to Key Vault](https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core5x#grant-your-app-access-to-key-vault)

Let me know if you have more questions.

**Comment by dluc** [comment]
@avanigupta thanks however I went through all the docs and tried different approaches and nothing in the docs would work. I think there's the assumption that one person would work with VS or have the CLI installed, which is not always the case.

This is the code that I ended up writing:

```csharp
// Use  Managed Identity by default, i.e. access the configuration service using
// the AAD identity of the Azure Resource where the code is deployed
TokenCredential credentials = new DefaultAzureCredential(
    new DefaultAzureCredentialOptions
    {
        // Required to run the code inside a Docker image
        // See https://github.com/Azure/azure-sdk-for-net/issues/17052
        ExcludeSharedTokenCacheCredential = true
    });

// Managed identities are not available when running in a dev environment
if (!this.IsAzureEnvironment())
{
    // these values are retrieved from environment variables
    credentials = new ClientSecretCredential(tenantId, clientId, clientSecret);
}

this.FetchConfiguration(configEndpoint, credentials);
```

**Comment by avanigupta** [comment]
@dluc, if you see the documentation of [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet), the first credential that is tried is the [EnvironmentCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet). This credential ultimately uses `ClientSecretCredential` for authentication. 

Please try setting `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` environment variables and the same `DefaultAzureCredential` should work for you in both local and Azure environments.

**Comment by dluc** [comment]
nice, I missed that part. Thank you!
