### ISSUE TITLE
Allow to skip KeyVault references

### ISSUE THREAD

**Issue by dluc** [Azure/AppConfiguration-DotnetProvider#264]
When setting up Azure App Config without `ConfigureKeyVault`, the configuration builder fails with an exception if the service contains a KeyVault reference, because it is unable to resolve those references. 

When developing locally without VisualStudio, where there's no support for managed identities and no VS authentication, one has to setup KeyVault credentials manually, using 3 environment variables (tenant id, client id, client secret), e.g.

```csharp
TokenCredential keyVaultCredentials = new ClientSecretCredential(
                    "...tenant id...", "...client id...", "...client secret...");
```

and then

```csharp
[...] options.ConfigureKeyVault(kvOptions => kvOptions.SetCredential(keyVaultCredentials);
```

Request: allow to run the builder skipping KeyVault references, so one can fetch "tenant id" and "client id" from the service, and then run the builder again with just one env var for the secret.

In any case, I think it would be useful allowing to skip the KeyVault references with a single option, making the client more flexible.

**Comment by avanigupta** [comment]
We have an API that allows you to custom resolve Key Vault references. Please see this issue for details and examples: #209

**Comment by avanigupta** [comment]
Feel free to reopen the issue if you have more questions.
