### ISSUE TITLE
IConfigurationRefresher still Preview

### ISSUE THREAD

**Issue by jsquire** [Azure/AppConfiguration-DotnetProvider#294]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#25639](https://github.com/Azure/azure-sdk-for-net/issues/25639).

## Details

Hi,
Is the IConfigurationRefresher interface still considered Preview? Other documentation (best practice guides etc..) would imply it is not and this document is flagged as preview incorrectly.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ce53b7-e6a5-83cc-4f30-992048ad6eef
* Version Independent ID: 6d7165dd-fa63-270f-f63a-516e628aada5
* Content: [IConfigurationRefresher Interface (Microsoft.Extensions.Configuration.AzureAppConfiguration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.iconfigurationrefresher?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/IConfigurationRefresher.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/IConfigurationRefresher.xml)
* Service: **azure-app-configuration**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by avanigupta** [comment]
Hello @Terry-Cornwell, thank you for reporting this. You are right, `IConfigurationRefresher` is not in preview anymore. The documentation has been updated to remove the preview tags.
