### ISSUE TITLE
UseAzureAppConfiguration should be put in Microsoft.Azure.Functions.Worker namespace

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#299]
The `UseAzureAppConfiguration` extension method should be put in the same namespace as `IFunctionsWorkerApplicationBuilder` so users don't have to add the additional namespace `Microsoft.Azure.AppConfiguration.Functions.Worker` to their code.

**Comment by zhenlan** [comment]
Looks like we should have put it under `Microsoft.Extensions.Hosting` like other extension methods

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.middlewareworkerapplicationbuilderextensions.usedefaultworkermiddleware

**Comment by avanigupta** [comment]
Yes, totally missed that! However, changing the namespace will be a breaking change. Since we have already released 5.0.0 version today, this would need to be fixed in 6.0.0 release.

**Comment by zhenlan** [comment]
Sorry, it was an oversight on my part.

The `Microsoft.Extensions.Hosting` namespace should be present in users' projects already, so nothing will really be breaking. I am wondering if we can roll a 5.0.1 just for this package quickly.

**Comment by avanigupta** [comment]
We can do a quick 5.0.1 release just for this package, and we can even deprecate 5.0.0 if needed.

**Comment by zhenlan** [comment]
Good idea. We can unlist 5.0.0 from nuget.org.
