### ISSUE TITLE
Dynamic Feature - Microsoft.FeatureManagement v3 support

### ISSUE THREAD

**Issue by jimmyca15** [Azure/AppConfiguration-DotnetProvider#315]
# Microsoft.FeatureManagement 3.0.0 support.

This configuration library provides a mechanism to use feature flags defined in Azure App Configuration with the Microsoft.FeatureManagement library. Version 3.0 of the Microsoft.FeatureManagement library will be introducing a [new schema](https://github.com/microsoft/FeatureManagement-Dotnet/blob/feature/v3/docs/schemas/FeatureManagement.v2.0.0.json) to define feature flags. This new schema will enable [dynamic features](https://github.com/microsoft/FeatureManagement-Dotnet/blob/feature/v3/README.md#dynamic-features) to be [defined](https://github.com/microsoft/FeatureManagement-Dotnet/blob/c816292a8e789be0c8b809c4d172afa05b491f9c/examples/FeatureFlagDemo/appsettings.json#L70).

To enable compatability with the new schema introduced in the Microsoft.FeatureManagement v3 library we should add an opt-in capability into our next 5.x preview package (E.g. 5.1.0-preview). This will enable two scenarios to work with the v3 Microsoft.FeatureManagement library:

* Use dynamic features defined in Azure App Configuration with the Microsoft.FeatureManagement library.
* Define feature flags in appsettings file using the new feature flag schema while simultaneously pulling feature flags from Azure App Configuration.

**Note**: Enabling this opt-in flag will cause feature flags to stop working with version 2.x of the feature management library.

### Opt-in flag

```
public class FeatureFlagOptions
{
    ...

    /// <summary>
    /// Forces feature flags to be written into the configuration system using the feature flag 2.0 schema introduced in
    /// Microsoft.FeatureManagement 3.0.0-preview.
    /// </summary>
    public bool EnablePreviewFeatureFlagSchema { get; set; }

    ...
}
```

### Usage

```
o.UseFeatureFlags(fo =>
{
    fo.EnablePreviewFeatureFlagSchema = true;
}
```

## Guidance

If you would like to try the 3.0.0-preview release of Microsoft.FeatureManagement and get feature flags as well as dynamic features from Azure App Configuration then enable this opt-in flag.

If you would like to continue using the stable 2.x versions of Microsoft.FeatureManagement then this flag can be ignored.

## Preview Functionality

This flag will only be available in preview versions of the 5.x Azure App Configuration .NET configuration provider.

**Comment by jimmyca15** [comment]
cc @zhenlan @avanigupta @mrm9084 

For any comments/suggestions

**Comment by mrm9084** [comment]
@jimmyca15 I know we have talked about this before, but is this only for the beta release? And will be removed once GAed?

**Comment by jimmyca15** [comment]
@mrm9084 Yes, the opt-in flag is only intended for a preview window. In future versions of the provider the opt-in flag will be removed, with the possibility of an opt-out flag to replace it.
