### ISSUE TITLE
Inconsistent exception handling when `AddAzureAppConfiguration` is invoked with `optional=true`

### ISSUE THREAD

**Issue by avanigupta** [Azure/AppConfiguration-DotnetProvider#318]
> My preference would be to fail no matter what for errors that come from invalid inputs, but that seems to contradict the documentation for the enabled flag.

My thoughts too. I think our "optional" behavior comes from the "optional" behavior of FileConfigurationProviders. For configuration files, this flag suppresses the exception when a file is not found. Anything else, like invalid syntax in file or empty file path still throws an exception when optional is true. 
Along similar lines, if optional is true for AppConfig provider, any errors that occur during `Build()` should not be suppressed (these are always due to invalid inputs). However, any errors that occur during `Load()` should be suppressed.

cc @zhenlan

_Originally posted by @avanigupta in https://github.com/Azure/AppConfiguration-DotnetProvider/pull/316#discussion_r857996210_

**Comment by zhenlan** [comment]
Just want to make sure this continues to work
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery

**Comment by avanigupta** [comment]
The idea is to throw on user input errors. Since the disaster recovery setup kicks in when there's a runtime error, the above doc instructions should still work.

**Comment by Eskibear** [comment]
> to fail no matter what for errors that come from invalid inputs,

It looks trivial by removing the check of optional [here](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/cd590f32b4efdbca0b55a5287b6609c7166871d7/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationSource.cs#L52-L65) within `Build()`.
As far I can tell, `FormatException` occurs when we fail to [parse](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/cd590f32b4efdbca0b55a5287b6609c7166871d7/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/ConnectionStringParser.cs#L28) the connection string for Endpoint part, and `InvalidOperationException` occurs when SDK fails to parse the connection string [when constructing a client](https://github.com/Azure/azure-sdk-for-net/blob/fbd045fd853edd9eb59def2b6f4c8d506cd822f1/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient_private.cs#L50-L53).
I would create a PR to make the change, and probably add more test cases related to guard the behavior. Let me know if you have more context info or any concern.

**Comment by Eskibear** [comment]
> any errors that occur during Build() should not be suppressed (these are always due to invalid inputs). However, any errors that occur during Load() should be suppressed.

It makes total sense.


BTW, below is an idiot question and maybe a little off-topic.
While I was browsing the impl, I find that Build() and Load() are always called together by  `builder.Build()` given how we usually use the snippet below. `AzureAppConfigurationSource.Build()` is called [here](https://github.com/dotnet/runtime/blob/9a7db5556f4ad892c611b2e174594db17fdec3af/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationBuilder.cs#L43-L51) and `AzureAppConfigurationProvider.Load()` is called [here](https://github.com/dotnet/runtime/blob/63a7a13190448f1ba5b3b449f1b9628d042d209d/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs#L32) when constructing ConfigurationRoot.
```c#
var builder = new ConfigurationBuilder().AddAzureAppConfiguration(...);
var config = builder.Build();
```
Given the idea to fail early, for obvious error like wrong format in user input, my gut feeling is to parse and check as early as in `AddAzureAppConfiguration(..)`. Why do we allow user to add an obvious wrong config source? The parsing should not be expensive I guess. Or perhaps to stay consistent with other config providers. Anyway it should not be a big problem and I just curious about it given my limited knowledge about .NET.

**Comment by avanigupta** [comment]
@Eskibear that's a valid point. We could fail earlier during `AddAzureAppConfiguration` for invalid connection strings. However, connection string parsing is not the only user input error we need to handle. There could be other user errors in setting up `AzureAppConfigurationOptions`, and we lazy initialize these options only if they are needed, ie., when `Build()` is invoked. So it makes more sense to validate the connection string during `Build` too.
