### ISSUE TITLE
CacheExpirationInterval only refreshes feature flags with no label

### ISSUE THREAD

**Issue by petekapakos** [Azure/AppConfiguration-DotnetProvider#321]
I have the following code in an asp.net core 6 web api:
````
.ConfigureWebHostDefaults(webBuilder =>
                    webBuilder.ConfigureAppConfiguration(config =>
                    {
                        var settings = config.Build();
                        config.AddAzureAppConfiguration(options =>
                            options.Connect("[Connection String]")
                                .UseFeatureFlags(featureFlagOptions =>
                                {
                                    featureFlagOptions.CacheExpirationInterval = TimeSpan.FromSeconds(10);
                                })
                                .Select(KeyFilter.Any, LabelFilter.Null)
                                .Select(KeyFilter.Any, settings["ASPNETCORE_ENVIRONMENT"])
                        );
````

I have created two configuration feature flags in azure configuration:
devfeature
nolabelfeature

'devfeature' has a label of 'Development'
'nolabelfeature' has no label.

When I run the application locally (or in the cloud), I am able to toggle the nolabelfeature setting on and off and the application responds accordingly after the expiration interval elapses.  However, when I toggle the devfeature setting on and off the application does not recognize that the feature flag has been updated.  The only way I'm able to get the application to recognize the new setting is by restarting the app service or stop and start debugging.

Both feature flag settings are set correctly on application startup, yet for some reason they only update if I don't set a label.

**Comment by avanigupta** [comment]
Hi @petekapakos, if no label is specified in the `FeatureFlagOptions.Select` clause, only null labels are loaded by default.

To select feature flags with specific labels, you can do this:

```
 .UseFeatureFlags(featureFlagOptions =>
  {
      featureFlagOptions.CacheExpirationInterval = TimeSpan.FromSeconds(10);
      featureFlagOptions.Select(KeyFilter.Any, LabelFilter.Null);
      featureFlagOptions.Select(KeyFilter.Any, settings["ASPNETCORE_ENVIRONMENT"]);
  })
```

Documentation here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.featuremanagement.featureflagoptions.select?view=azure-dotnet
