### ISSUE TITLE
Proposal to rename refresh APIs 

### ISSUE THREAD

**Issue by avanigupta** [Azure/AppConfiguration-DotnetProvider#350]
Due to some confusion around the use of the word "cache" in our API names, we could change the following APIs to better reflect their functionality:
AzureAppConfigurationRefreshOptions
- SetCacheExpiration -> `SetRefreshInterval`

FeatureFlagOptions
- CacheExpirationInterval  property -> Deprecate the property in favor of a new `SetFeatureFlagRefreshInterval` method

This would help clarify that the provided TimeSpan is only used to trigger a new refresh operation. If nothing has changed on the server, configuration values being used by the application continue to be valid even after this time has passed - values don't "expire".

The proposed name changes also align with our existing [AzureAppConfigurationKeyVaultOptions.SetSecretRefreshInterval](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationkeyvaultoptions.setsecretrefreshinterval?view=azure-dotnet) API. 

cc @drago-draganov @zhenlan

**Comment by amerjusupovic** [comment]
Completed and will be part of the next preview release
