### ISSUE TITLE
A/B Testing or gray deployment support

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration-DotnetProvider#353]
With A/B Testing or gray deployment support, we can validate configuration changes in small scope before rolling out to all service instances.
May I know any plan to support to?

**Comment by avanigupta** [comment]
Hi @lissdy, this tutorial can help you get started on Azure App Configuration Feature Management: https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core

**Comment by avanigupta** [comment]
Following up on https://github.com/Azure/AppConfiguration/issues/681.
