### ISSUE TITLE
Provide custom secret resolver (SetSecretResolver) with additional resolution context

### ISSUE THREAD

**Issue by maskati** [Azure/AppConfiguration-DotnetProvider#360]
The library does not currently make it easy to support access to secrets where resolution is based on configuration metadata (for example label or tags). The `SetSecretResolver` configuration takes a delegate that provides as context only `KeyVaultSecretIdentifier.SourceId` (URI to the Key Vault secret).

Currently [GetSecretValue](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/60a3f25327ac4688c7ad723fc7b2c55c70d76f0b/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureKeyVaultReference/AzureKeyVaultSecretProvider.cs#L38) also receives as context the associated AAC configuration `ConfigurationSetting.Key`, which could be provided to the custom resolver.

The upstream [ProcessKeyValue](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/60a3f25327ac4688c7ad723fc7b2c55c70d76f0b/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureKeyVaultReference/AzureKeyVaultKeyValueAdapter.cs#L30) also receives the full [ConfigurationSetting](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationSetting.cs) including the key, label, (key vault reference) value, and tags.

Consider an overload of `SetSecretResolver` that allows injecting additional resolution context, ideally providing the full `ConfigurationSetting`.

**Comment by avanigupta** [comment]
Hello @maskati, we are working on a new API that gives users access to the full `ConfigurationSetting` retrieved from AppConfig. You'd be able to make any modifications to the `ConfigurationSetting` object before we run `ProcessKeyValue` on it. Would this address your issue: https://github.com/Azure/AppConfiguration-DotnetProvider/issues/157

**Comment by maskati** [comment]
@avanigupta that sounds great, thanks for the confirmation!
