### ISSUE TITLE
Add support to load configuration from snapshots

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration-DotnetProvider#387]
API proposal:

```cs
public AzureAppConfigurationOptions Select(string snapshotName)
```

cc: @avanigupta @jimmyca15 @drago-draganov

**Comment by jimmyca15** [comment]
That doesn't conflict with our existing API

`public AzureAppConfigurationOptions Select(string keyFilter, string labelFilter = LabelFilter.Null)` ?

**Comment by zhenlan** [comment]
Good catch. It will. How about

```cs
public AzureAppConfigurationOptions SelectSnapshot(string name)
```

**Comment by jimmyca15** [comment]
Sounds good to me.
