### ISSUE TITLE
Is error handling for "_ = _refresher.TryRefreshAsync();" needed?

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration-DotnetProvider#399]
`_ = _refresher.TryRefreshAsync();` is to refresh configuration without waiting, as the document mentioned https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core6x#request-driven-configuration-refresh, the operation will not block or slow down the incoming request that triggered the refresh. This is great,
but may I double confirm as a consumer, do I need to take care of the error handling? Will the unwaited task lead to any unobserved exceptions?

**Comment by amerjusupovic** [comment]
Hi @lissdy, calling `TryRefreshAsync` without waiting does not require additional error handling on your behalf. Any exceptions thrown during refresh are handled by this method.
