### ISSUE TITLE
Changelog version 6.0.0 ?

### ISSUE THREAD

**Issue by Rutix** [Azure/AppConfiguration-DotnetProvider#402]
Hi,

Last week version 6.0.0 was published on nuget:

https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore#versions-body-tab

but I can't find the changelog. The releases on github only go until 5.2.0 (https://github.com/Azure/AppConfiguration-DotnetProvider/releases)

It's now kinda hard to see if this contains breaking changes for us or not.

**Comment by amerjusupovic** [comment]
Hi @Rutix, I apologize for the delay on the release notes but they should be available now at https://github.com/Azure/AppConfiguration-DotnetProvider/releases.

**Comment by Rutix** [comment]
Thanks @amerjusupovic this really helps! I am closing the issue :)
