### ISSUE TITLE
Mutiple sentinel keys don't refresh at the same frenqency?

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration-DotnetProvider#407]
I have set multiple sentinel keys, for any sentinel change, the configuration provider should load the selected configurations. 

![image](https://user-images.githubusercontent.com/3861170/234268396-8e7487d9-6240-4114-ba16-3dc22af363c3.png)

But I check the service log AACHttpRequest and noticed the first sentinel key refresh frequency works as expected, sending HTTP request every 2 mins, but the second sentinel refresh frequency is lower than the first one, and the last one is even lower than the second one.

All sentinel keys exist in configuration store.

![image](https://user-images.githubusercontent.com/3861170/234498431-a2143bea-8a88-45a2-b456-ab90ee74a462.png)

Sometimes I would only update the last sentinel key, this makes the configuration change take effects much longer than expected.

It looks like a bug to me, may I confirm if is this expected?

version: 5.1.0

**Comment by amerjusupovic** [comment]
This is currently being addressed in the mentioned issue above, so I'm closing it here.
