### ISSUE TITLE
AzureAppConfigurationRefreshOptions - Add support for ignoring refresh failures

### ISSUE THREAD

**Issue by ivanalfonso-msft** [Azure/AppConfiguration-DotnetProvider#433]
Currently, you can specify the optional at the top level, but would be nice to have this as required, but indicate failures on refresh to be ignored. Something like:

```
config.AddAzureAppConfiguration(options =>
{
  options.Connect(...).ConfigureRefresh(refresh =>
  {
    refresh.IgnoreFailures = true;
  });
}, optional: false);
```

Is something like this already available? If not, does it make sense to add such functionality?

Thank you.

**Comment by zhenlan** [comment]
If you use App Configuration middleware for ASP.NET Core, failures during configuration refresh are always ignored.

If you call refresh in your code, you can use `TryRefreshAsync` to ignore the error or use `RefreshAsync` to get exceptions in case an error occurs.

**Comment by ivanalfonso-msft** [comment]
I see, appreciate your prompt help. Thank you.
