### ISSUE TITLE
If feature flags are the only filters then all keys are requested

### ISSUE THREAD

**Issue by ghelyar** [Azure/AppConfiguration-DotnetProvider#459]
If the only key-value filters specified start with `.appconfig.featureflag/` then the client requests `key=*`.

For example, this will display all configuration keys, including all flags:
```csharp
var config = new ConfigurationBuilder().AddAzureAppConfiguration(options =>
{
    options.Connect("...");
    options.UseFeatureFlags(options => options.Select("flag1,.appconfig.featureflag/flag2")); // side note, csv is weird here
}).Build();
Console.WriteLine(config.GetDebugView());
```

The only way I have found to prevent this is to put a dummy filter key in e.g.
```csharp
var config = new ConfigurationBuilder().AddAzureAppConfiguration(options =>
{
    options.Connect("...")
        .Select("DOESNOTEXIST", LabelFilter.Null);
    options.UseFeatureFlags(options => options.Select("flag1,.appconfig.featureflag/flag2"));
}).Build();
Console.WriteLine(config.GetDebugView());
```

This is caused by the default query logic defined in [AzureAppConfigurationProvider.LoadSelectedKeyValues](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/3e4de83d71b12fcb952cd20d19712dd232522ced/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationProvider.cs#L615)

I assume this was done so that adding feature flags to something that previously had no filters should not prevent it from reading what it already had, but it makes filtering which feature flags are read difficult.

It all still works, it's just making more requests than expected to AAC, which causes performance/throttling issues.

**Comment by amerjusupovic** [comment]
Hi @ghelyar, at the moment we still recommend using a dummy key filter like `.Select("_")` to prevent the default query. Are you saying that you've noticed performance/throttling issues even when using this solution? I wouldn't expect this select call to have a noticeable effect on an application.

**Comment by ghelyar** [comment]
No I haven't had throttling since implementing this, but I did not find it very clear that this needed doing at all.

I only did this because I got unexpected throttling which caused some problems in production, then turned on EventSource tracing and noticed the excessive requests it was making, then looked thought the source to find why it was requesting everything even after I specifically told it to filter.

Also `.Select("flag1").Select("flag2")` causes it to make multiple requests, which I was not expecting, hence the CSV in the code above, but because it prefixes the first flag, CSV filtering needs to add the prefix between each subsequent flag only.

It's all just a bit counterintuitive, and doesn't seem to do what you ask it to do unless you really dig into the implementation to get a deep understanding of how it works so that you can work around all the quirks.

**Comment by amerjusupovic** [comment]
I understand, we didn't make it clear that key-values would be selected by default in at least some of the documentation, so it's a valid concern. That's something I would consider at least adding to the method summary in the code.

As far as selecting multiple flags, I'll look into how we could make the usage of `FeatureFlagOptions.Select` with commas clearer and if we can remove the prefix on each subsequent flag name. You can also use a prefix like `NumberedFlags:*` to select multiple flags with one call to `Select` to make things a bit cleaner if that's possible for your scenario.

Currently, this dummy filter workaround has only been mentioned [here](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/182#issuecomment-1536711679) as far as I'm aware. 

I'll make sure to update this thread and link any related pull requests made as a result of this. I hope that answers your questions, let me know if there's anything else we should address.

**Comment by ghelyar** [comment]
One possible implementation of the select could be to take a params array, gather the filters and `Chunk(5)` and `string.Join` them into CSV format to reduce requests, but it doesn't really help when it's also requesting `*`.

You could change `StartsWith(".appconfig.featureflag/")` to `Equals(".appconfig.featureflag/*")` so that if you specify any filter then it doesn't request `*` but that means that if you specify a feature flag filter and it no normal configuration filters, it also excludes them, which is also unexpected.

Really it's just that the API implies that there are two independent filter sets but in reality there is only one.

I can't just flag name prefix in my particular case, because flags can be used across multiple services so the name can't include the service name, I can't use labels because we're using labels for environmental overrides. As far as I can tell AAC is designed for you to have one AAC for each service but this is quite a big a maintenance burden for systems with many services and environments, and the whole point of us using this was supposed to be a single central source of truth.
