### ISSUE TITLE
[BUG] After Upgrading AzureAppConfiguration AppInsights receives suddenly status 302 for refresh key checks

### ISSUE THREAD

**Issue by jsquire** [Azure/AppConfiguration-DotnetProvider#519]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#42025](https://github.com/Azure/azure-sdk-for-net/issues/42025).

### Library name and version

Microsoft.Azure.AppConfiguration.AspNetCore 7.0.0

### Describe the bug

After upgrading from Microsoft.Azure.AppConfiguration.AspNetCore V5.1.0 to V7.0.0
and Microsoft.Extensions.Configuration.AzureAppConfiguration V5.1.0 to V7.0.0

I am receiving suddenly Refresh Key Check Warnings of status 304 every 5 seconds (my refresh intervall) inAzure App Insights.

This is flooding my loggings and should not be so.

### Expected behavior

No 304 Warnings should be shown in AzureAppInsights for Refresh Key Checks where the when the Sentinel Values hasn't changed

### Actual behavior

The 304 Warning for Refreshkey Changes is suddenly appearing in my logs.

<img width="835" alt="Screenshot 2024-02-16 at 09 12 59" src="https://github.com/Azure/azure-sdk-for-net/assets/110200/d01417ec-5620-454d-bb8c-64837a7572a7">

### Reproduction Steps

The internal call to AppConfiguration Refresh Key is causing returning 304 which is logged.
https://[hidden].azconfig.io/kv/%21Trigger?api-version=2023-10-01

**Comment by amerjusupovic** [comment]
@mpodonyi This issue looks very similar to another we've gotten linked [here](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/514). Upgrading our dependency to the newest version of `Azure.Data.AppConfiguration` is when 304s started showing as failures, and I've reached out to the Application Insights team for support on this issue. If you can also send feedback to Application Insights under the "Help" tab for your resource in the Azure portal, I think it would help them get more context on how this issue arose.

I don't see a way to fix this from our end at the moment, but I hope to find an answer soon.

**Comment by amerjusupovic** [comment]
Closing this issue and keeping #514 open to track this
