### ISSUE TITLE
Detect Blazor and ASP.NET applications for request tracing

### ISSUE THREAD

**Issue by amerjusupovic** [Azure/AppConfiguration-DotnetProvider#569]
Knowing the approximate proportion of ASP.NET applications out of all customers could be helpful for understanding which features are most important to our users, and which kinds of applications are using certain features.

**Comment by zhenlan** [comment]
@mrm9084 and I were discussing the flask and django usage for python applications. It's good if we can design something to capture the framework information.

**Comment by zhiyuanliang-ms** [comment]
Apps utilizing Blazor are not fundamentally different from other types of ASP.NET apps. There's no fool proof method to detect whether users are using Blazor or not. According to https://github.com/dotnet/aspnetcore/issues/56633

ASP.NET Core supports mixing various UI frameworks together, so you could even have an app that utilizes both Razor Pages and Blazor. In fact, prior to .NET 8, most Blazor Server apps also used Razor Pages to host the root Blazor component. There isn't much that a class library can do to observe these types of detailed characteristics about the app. 

The best we can do is to check which assemblies have been loaded (e.g. SignalR related stuff), but that's only a heuristic and subject to change at any point in the future.

**Comment by zhiyuanliang-ms** [comment]
Discussed with @jimmyca15 and @rossgrambo offline. We are going to collect whether there is `Microsoft.AspNetCore.SignalR` assembly. This assembly will be loaded as long as Blazor is unused. If we collect data showing that many people are using SignalR, it doesn't necessarily mean our users are using Blazor apps. However, if our data shows that few people are using SignalR, it definitely means the number of our users using Blazor apps won't be higher than this. Therefore, collecting information about SignalR can still provide us with some useful insights.
