### ISSUE TITLE
Optional flag has incorrect documentation

### ISSUE THREAD

**Issue by kaunglvlv** [Azure/AppConfiguration-DotnetProvider#593]
Back in v7.0, `ArgumentException` was still being thrown even if `optional` was set to `true` (which I don't love).  However, the documentation for the arg still says the exception is suppressed.

> Determines the behavior of the App Configuration provider when an exception occurs while loading data from server. If false, the exception is thrown. If true, the exception is suppressed and no settings are populated from Azure App Configuration.

**Comment by amerjusupovic** [comment]
@kaunglvlv Thanks for pointing that out, I think for now we can at least update this description to indicate that the provider will throw ArgumentException for any invalid parameters passed in.
